[tool.black]
line-length = 88
include = ".pyi?$"
exclude = """
(
  /(
    | .github
    | .pytest_cache
    | venv
  )/
)
"""

[tool.pytest.ini_options]
addopts = "-vv -ra -q "
testpaths = ["test"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
log_file = "pytest.log"
log_file_date_format = "%Y%b%d %H:%M:%S"
log_file_format = "%(asctime)s %(levelname)s %(message)s"
log_file_level = "DEBUG"


[tool.coverage.run]


[tool.coverage]
path = "dirtree2json/"
